# Generated by Django 4.0.2 on 2022-02-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffworkwage',
            name='work_staff_approval_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffworkwage',
            name='completion_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffworkwage',
            name='wage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staffworkwage',
            name='wage_given',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
