# Generated by Django 4.0.2 on 2022-02-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
