# Generated by Django 4.0.2 on 2022-02-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_advance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffstatuscompletion',
            name='work_staff_comp_app_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
