# Generated by Django 4.0.2 on 2022-02-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_staff_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='order',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='staff',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
        ),
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='work',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='api.work'),
        ),
    ]
