# Generated by Django 4.0.2 on 2022-02-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tmpwork_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpwork',
            name='quantity',
            field=models.CharField(default='', max_length=5),
        ),
    ]
