# Generated by Django 4.0.2 on 2022-02-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orderworkstaffstatuscompletion_work_staff_comp_app_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='ordermaterial',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderwork',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderwork',
            name='work',
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='material_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='order_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderwork',
            name='order_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderwork',
            name='work_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
