# Generated by Django 4.0.2 on 2022-02-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tmpwork_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpmaterial',
            name='cust_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
