# Generated by Django 4.0.2 on 2022-02-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orderworkstaffassign_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderworkstafftaken',
            name='taken_stage',
            field=models.CharField(blank=True, choices=[('cutting', 'CUTTING'), ('stitching', 'STITCHING'), ('hook', 'HOOK'), ('overlock', 'OVERLOCK')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderworkstafftaken',
            name='work',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.work'),
        ),
    ]
