# Generated by Django 4.0.2 on 2022-02-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tmpmaterial_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='assign_date_time',
            field=models.DateTimeField(default=''),
        ),
    ]
