# Generated by Django 4.0.2 on 2022-02-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderworkstafftaken_taken_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderworkstafftaken',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderworkstafftaken',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='orderworkstafftaken',
            name='work',
        ),
    ]
