# Generated by Django 4.0.2 on 2022-02-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tmpwork_work_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpmaterial',
            name='material_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
