# Generated by Django 4.0.2 on 2022-02-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orderworkstaffassign_assign_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photot',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
