# Generated by Django 4.0.2 on 2022-02-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_staff_photot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='staff',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
        ),
    ]
