# Generated by Django 4.0.2 on 2022-02-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tmpmaterial_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaterial',
            name='amount',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='quantity',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderwork',
            name='amount',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderwork',
            name='quantity',
            field=models.CharField(default='', max_length=20),
        ),
    ]
