# Generated by Django 4.0.2 on 2022-02-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ordermaterial_amount_ordermaterial_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaterial',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderwork',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
