# Generated by Django 4.0.2 on 2022-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_orderworkstaffassign_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='assign_date_time',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='assign_stage',
            field=models.CharField(choices=[('cutting', 'CUTTING'), ('stitching', 'STITCHING'), ('hook', 'HOOK'), ('overlock', 'OVERLOCK')], default='', max_length=50),
        ),
    ]
