# Generated by Django 4.0.2 on 2022-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_orderworkstaffassign_assign_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='assign_date_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
