# Generated by Django 4.0.2 on 2022-02-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_ordermaterial_amount_alter_orderwork_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaterial',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderwork',
            name='amount',
        ),
    ]
