# Generated by Django 4.0.2 on 2022-02-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_orderworkstaffassign_assign_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='assign_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
