# Generated by Django 4.0.2 on 2022-02-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_ordermaterial_amount_remove_orderwork_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaterial',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderwork',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
