# Generated by Django 4.0.2 on 2022-02-27 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='staff',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
        ),
    ]
