# Generated by Django 4.0.2 on 2022-02-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orderworkstaffassign_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_assigned', to='api.order'),
        ),
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='staff',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assigned', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='work_assigned', to='api.work'),
        ),
    ]
