# Generated by Django 4.0.2 on 2022-02-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_orderworkstaffassign_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='work',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_assigned', to='api.work'),
        ),
    ]
