# Generated by Django 4.0.2 on 2022-02-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_orderworkstaffassign_assign_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderworkstaffassign',
            old_name='order',
            new_name='order_ref',
        ),
        migrations.RenameField(
            model_name='orderworkstaffassign',
            old_name='staff',
            new_name='staff_ref',
        ),
        migrations.RenameField(
            model_name='orderworkstaffassign',
            old_name='work',
            new_name='work_ref',
        ),
    ]
