# Generated by Django 4.0.2 on 2022-02-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_order_orderworkstaffassign_order_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='order_ref',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_assigned', to='api.order'),
        ),
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='staff_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assigned', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='orderworkstaffassign',
            name='work_ref',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, related_name='work_assigned', to='api.work'),
        ),
    ]
