# Generated by Django 4.0.2 on 2022-02-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_orderworkstaffassign_order_ref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderworkstaffassign',
            old_name='order_ref',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderworkstaffassign',
            old_name='staff_ref',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='orderworkstaffassign',
            old_name='work_ref',
            new_name='work',
        ),
    ]
